[build]
builder = "NIXPACKS"
buildCommand = "pip install -r requirements.txt"

[deploy]
startCommand = "python app.py"
healthcheckPath = "/"
healthcheckTimeout = 100

[environments.production]
numReplicas = 1
port = 7860