# Railway configuration
build = { builder = "DOCKERFILE", dockerfilePath = "Dockerfile.dockerfile" }
deploy = { 
  startCommand = "python app.py",
  restartPolicyType = "ON_FAILURE",
  restartPolicyMaxRetries = 10
}